### ISSUE TITLE
weakSelf宏定义报错 typeof缺失？

### ISSUE THREAD

**Issue by YelCode** [meitu/MTHawkeye#1]
![image](https://user-images.githubusercontent.com/13357868/56401077-bcdaac80-6289-11e9-8b84-e501e31fd8d5.png)

**Comment by euanchan** [comment]
这是你项目内自己的代码吧，Hawkeye 内没有这两个宏

**Comment by YelCode** [comment]
我也觉得莫名其妙 就是引入这个框架后 报错
是不是改了什么项目配置 修改了关于c++的一些配置

**Comment by euanchan** [comment]
代码调用有做了什么改动
