### ISSUE TITLE
pod 貌似搜不到这个库

### ISSUE THREAD

**Issue by TonyWang-hub** [meitu/MTHawkeye#10]
![image](https://user-images.githubusercontent.com/12796568/56874501-d4294f00-6a6c-11e9-9faa-5eda7790ae87.png)
后面删除了索引 rm ~/Library/Caches/CocoaPods/search_index.json
重新搜索 依然是搜不到

**Comment by Jason8Zhang** [comment]
pod update 一下应该就好了

**Comment by euanchan** [comment]
先 `pod repo update`，更新完成后再搜索
