### ISSUE TITLE
使用该库进行pod install时生成以下提示信息

### ISSUE THREAD

**Issue by zhipengbird** [meitu/MTHawkeye#13]
**Describe the bug**
在不添加该库时，不会产生以下信息，只有在添加该库时出现
**Log**
[!] The `StarMakerLite [Release]` target overrides the `CLANG_CXX_LANGUAGE_STANDARD` build setting defined in `Pods/Target Support Files/Pods-StarMakerLite/Pods-StarMakerLite.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

目前项目中`CLANG_CXX_LANGUAGE_STANDARD `的值为 CLANG_CXX_LANGUAGE_STANDARD = c++11

暂时不清楚是本库是否有某些参数与项目的设置有冲突

**Comment by euanchan** [comment]
MTHawkeye 依赖的 MTGLDebug 有使用 C++11 语法，工程设置上，可以根据提示，加上 $(inherited)

**Comment by zhipengbird** [comment]
建议在你的podspec文件中加上相关的配置，而不是用户工程来设置，你可以参考下这个库的设置
https://github.com/Tencent/MMKV/commit/3b2ecbe26ccb1c47fe5383060df537d4891f5ba4

**Comment by euanchan** [comment]
@zhipengbird MTGLDebug 3.1.1 版本已做了处理
