### ISSUE TITLE
加入该库，目前发现调用堆栈查看不了了

### ISSUE THREAD

**Issue by zhipengbird** [meitu/MTHawkeye#15]
**Describe the bug**
调用堆栈查看不了了

**Comment by euanchan** [comment]
是指暂停调试时 Xcode  的方法调用栈？
开启 ObjC CallTrace 功能后会覆盖方法，平时不要开启。这个在开启的时候有弹窗提示，注意看下，文档里也有。

**Comment by panmingyang2009** [comment]
久未回复，应该是开启了 CallTrace 导致堆栈无法查看，关闭 issue
