### ISSUE TITLE
README上没有找到注册插件的方法

### ISSUE THREAD

**Issue by cjlcooper** [meitu/MTHawkeye#16]
**Describe the bug**

**Log**
There are two ways to get the running log of MTHawkeye:
A: Filter the Xcode Console log, they are start with `[hawkeye]`
B: Under the `com.meitu.hawkeye` folder in sandbox, the log was store as `log.mtlog` & `log.mmap2`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

 - Xcode Version: [e.g. 10.2]

**Additional context**

**Comment by cjlcooper** [comment]
addDefaultUIClientMainPanelPluginsInto方法中mainPanelPlugins最终并没有使用到，不太明白怎么添加自定义的插件。

**Comment by cjlcooper** [comment]
添加插件方法在MTHawkeyeUIClient方法中，已找到。

**Comment by panmingyang2009** [comment]
OK
