### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid number value (infinite) in JSON write'

### ISSUE THREAD

**Issue by YakirLove** [meitu/MTHawkeye#17]
加载有些网页的时候，出现崩溃

**Comment by YakirLove** [comment]
![558931C1-8EBC-48BE-B78F-272D0DB26010](https://user-images.githubusercontent.com/4088129/58795243-bc755580-862c-11e9-83f1-dd1280cd6efc.png)

**Comment by euanchan** [comment]
下次再出现能否控制台打印下详细的堆栈信息，如果有上下文信息的话能帮助我们更快的确认问题

**Comment by euanchan** [comment]
未有更详细的上下文信息，无法确定是否是由应用本身引起，先关闭
