### ISSUE TITLE
网络模拟出错

### ISSUE THREAD

**Issue by zhipengbird** [meitu/MTHawkeye#22]
**Describe the bug**
进入Network Monitor必现
**Log**
[Bugly]  Trapped uncaught exception 'NSUnknownKeyException', reason: '[<NSURLSessionTaskMetrics 0x283eba430> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key redirectCount.' 
(
	0   CoreFoundation                      0x00000001a0ba2a04 2D4D4E9A-884C-31FE-90BE-B324E7B02A3F + 1223172
	1   libobjc.A.dylib                     0x00000001a10af4fc objc_exception_throw + 56
	2   CoreFoundation                      0x00000001a0aa81e4 2D4D4E9A-884C-31FE-90BE-B324E7B02A3F + 197092
	3   Foundation                          0x00000001a06d31f8 6511D0A1-2D67-36FA-BA0E-8FB08A6380FE + 205304
	4   StarMaker                           0x00000001029fd3a8 +[MTHNetworkTransaction transactionFromPropertyDictionary:] + 3276
	5   StarMaker                           0x00000001029de070 __51-[MTHNetworkRecordsStorage readNetworkTransactions]_block_invoke.52 + 268
	6   Foundation                          0x00000001a06c50fc 6511D0A1-2D67-36FA-BA0E-8FB08A6380FE + 147708
	7   Foundation                          0x00000001a0720fb8 6511D0A1-2D67-36FA-BA0E-8FB08A6380FE + 524216
	8   StarMaker                           0x00000001029dd848 -[MTHNetworkRecordsStorage readNetworkTransactions] + 532
	9   StarMaker                           0x00000001029cd41c -[MTHNetworkMonitorViewModel loadTransactionsWithInspectComoletion:] + 116
	10  StarMaker                           0x00000001029c73cc __51-[MTHNetworkMonitorViewController loadTransactions]_block_invoke + 216
	11  libdispatch.dylib                   0x00000001093e1874 _dispatch_call_block_and_release + 24
	12  libdispatch.dylib                   0x00000001093e2c50 _dispatch_client_callout + 16
	13  libdispatch.dylib                   0x00000001093e5354 _dispatch_queue_override_invoke + 876
	14  libdispatch.dylib                   0x00000001093f41d8 _dispatch_root_queue_drain + 376
	15  libdispatch.dylib                   0x00000001093f4b00 _dispatch_worker_thread2 + 156
	16  libsystem_pthread.dylib             0x00000001a13effcc _pthread_wqthread + 416
	17  libsystem_pthread.dylib             0x00000001a13f2aa0 start_wqthread + 8
)

**To Reproduce**
进入Network Monitor

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

 - Device:  iPhone8
 - OS: iOS13
 - Xcode Version: xcode11

**Additional context**

**Comment by euanchan** [comment]
感谢反馈，iOS 13 下 NSURLSessionTaskMetrics 的内部结构修改了，导致调用 setValue:forKey:"redirectCount" 失效，我看下怎么修改好些。

**Comment by hello-david** [comment]
iOS 13 Beta2中NSURLSessionTaskMetrics ivars变更
```
<NSURLSessionTaskMetrics: 0x281f18920>:
in NSURLSessionTaskMetrics:
	__metrics (__CFN_TaskMetrics*): nil
in NSObject:
	isa (Class): NSURLSessionTaskMetrics (isa, 0x1a1d07c2e75)

(lldb) ivars [__CFN_TaskMetrics new]
<__CFN_TaskMetrics: 0x283918cc0>:
in __CFN_TaskMetrics:
	_lock (struct os_unfair_lock_s): {
		_os_unfair_lock_opaque (unsigned int): 0
	}
	_ignoreNextRedirection (BOOL): NO
	_completed (BOOL): NO
	_UUID (NSUUID*): nil
	_identifier (unsigned long): 0
	_transactionMetrics (NSMutableArray*): nil
	_createTime (double): 0
	_firstResumeTime (double): 0
	_completeTime (double): 0
	_options (long): 0
	_schedulingTier (long): 0
	_currentTransactionMetrics (__CFN_TransactionMetrics*): nil
	_sessionMetrics (__CFN_SessionMetrics*): nil
in NSObject:
	isa (Class): __CFN_TaskMetrics (isa, 0x1a1d07c2385)
```
