### ISSUE TITLE
实现NSURLSessionDelegate方法会监控不到数据

### ISSUE THREAD

**Issue by qcliwei** [meitu/MTHawkeye#26]
你好，我在Network Inject Test中
MTURLConnectionInjectTestViewController类中 
实现了
`- (void)URLSession:(NSURLSession *)session dataTask:(nonnull NSURLSessionDataTask *)dataTask didReceiveResponse:(nonnull NSURLResponse *)response completionHandler:(nonnull void (^)(NSURLSessionResponseDisposition))completionHandler`
点击URLSession Without delegate选项，监控不到数据

还有在MTHNetworkObserver中injectIntoURLSessionTaskCreator和injectIntoNSURLConnectionCreator方法中，都有
if (TRUE)的写法，这个判断起什么作用？

 - Device: XR
 - OS: 12.2
 - Xcode Version: 10.2.1

**Comment by euanchan** [comment]
感谢反馈，这边已复现问题。

if (TRUE) 是遗留的测试代码，false 分支可以直接忽略

**Comment by hello-david** [comment]
根据API[文档](https://developer.apple.com/documentation/foundation/nsurlsessiondatadelegate/1410027-urlsession?language=objc)的说明。实现了这个回调函数需要实现它的completionHandler定义接下去这个Task的动作。
```
- (void)URLSession:(NSURLSession *)session
          dataTask:(NSURLSessionDataTask *)dataTask
didReceiveResponse:(NSURLResponse *)response
 completionHandler:(void (^)(NSURLSessionResponseDisposition))completionHandler {
    
    if (completionHandler) {
        completionHandler(NSURLSessionResponseAllow);
    }
}
```
