### ISSUE TITLE
长时间后台进入前台，偶现ANR记录异常

### ISSUE THREAD

**Issue by lalalafq** [meitu/MTHawkeye#28]
**Describe the bug**
长时间后台进入前台，偶现ANR记录异常

**Log**
custom-time-event,1562657739.233881,{"event":"App::DidEnterBackground","time":1562657739.233881}
（中间大量CPU，MEM已忽略）
custom-time-event,1562671401.548742,{"event":"App::WillEnterForeground","time":1562671401.5487421}
view-ctrl,8,{"loadViewExit":1562671401.5686679,"didLoadExit":1562671401.568696,"loadViewEnter":1562671401.568583,"didAppearExit":1562671401.688776,"initExit":1562671401.567296,"willAppearExit":1562671401.5822461,"didLoadEnter":1562671401.568692,"willAppearEnter":1562671401.5822361,"name":"HXKaiPingAdRootViewController","didAppearEnter":1562671401.6887641}
custom-time-event,1562671401.795998,{"event":"App::DidBecomeActive","time":1562671401.7959981}
anr,1562671401.899392,{"biases":"4.884004592895508","duration":"5023540.706038475","stacks":[{"titleframe":"0x104b9565f","time":1562671401.796412,"stackframes":"0x2063cfea4,0x2063cf37b,0x20624f603,0x20624faa3,0x206497e9f,0x20740aab7,0x2071d256b,0x2071e0333,0x207410a63,0x210d07bdb,0x20627e483,0x20625e743,0x210d07a77,0x210d05747,0x233a3faf3,0x104b9565f,0x2067b483b,0x2067b4807,0x2067b3cf7,0x2067b39a3,0x20672bb7f,0x2067b342f,0x2071c4c9f,0x233a16a63,0x2332bdfc3,0x2332bee23,0x2332bdd7b,0x2332c2c67,0x233608727,0x20927d6e3,0x20627e483,0x2062553df,0x2092bba9b,0x2092bb727,0x2092bbd43,0x2067d60df,0x2067d605f,0x2067d5943,0x2067d080f,0x2067d00df,0x208a49583,0x233a20bff,0x1024472eb,0x20628ebb3"}]}

**To Reproduce**
1. 进入后台
2. 等待一段时间
3. 在WillEnterForeground，代码执行开屏广告处理
4. 出现异常ANR

**Expected behavior**
没有这条ANR信息

**Additional context**
1.为什么会有一条长达5023540.706038475耗时的ANR信息
2.为什么这段耗时和前后台切换的差值出入较大

**Comment by hello-david** [comment]
1.写到文件中的anr record中biases与duration字段的单位是毫秒。
2.进入后台后anr处理流程存在异常

**Comment by euanchan** [comment]
@lalalafq 原来 ANR 的实现利用了 afterWaiting/beforeTimers/beforeSources 的回调事件作为起始时间，beforeWaiting 的回调事件作为结束时间。
在进入后台，停留一段时间等待进程挂起后，再回到 App，此时 App 会回调 beforeTimes/sources 开始新一轮的 runloop，但是这里的时间为 App 挂起前的时间。

e8c97bdde389e9c56f678b82bd9d30756c0c868a 针对这种情况作了特殊处理，在后台时，忽略开头的的起始时间：
根据临近 runloop activity 的偏差，遇到第一次变动较大的偏差时，记录并将起始时间挪到这个点上。
