### ISSUE TITLE
找不到flex文件

### ISSUE THREAD

**Issue by yanqiangS** [meitu/MTHawkeye#3]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/16951446/56707837-18ef7600-674d-11e9-9d55-f36a708c014e.png">
手动添加过也不行

**Comment by euanchan** [comment]
清除下工程，重开 Xcode，然后重新 pod install 在试下

**Comment by euanchan** [comment]
@UiMer 问题是否已解决呢？

**Comment by JonyFang** [comment]
> 清除下工程，重开 Xcode，然后重新 pod install 在试下

![image](https://user-images.githubusercontent.com/12381169/56779701-c5ddf780-680e-11e9-81e0-0ed2c69beac9.png)

`pod install `前需要 移除下` Podfile.lock `文件

原因：`MTGLDebug `中` tag 版本`当前只有` 3.0.0 `，无` Podfile.lock `文件中对应的` 2.1.0 `

![image](https://user-images.githubusercontent.com/12381169/56779723-e6a64d00-680e-11e9-8039-8c234f071e8f.png)

**Comment by euanchan** [comment]
@JonyFang 误提交了内网的版本依赖，我修正下，本地不更新代码的话可直接执行下

```sh
pod update MTGLDebug
```
