### ISSUE TITLE
ANR Trace crash

### ISSUE THREAD

**Issue by guesspalm** [meitu/MTHawkeye#37]
**Describe the bug**
为了测试ANR 在点击事件中做了100w次循环 然后crash了

**Log**

*** Assertion failure in -[MTHawkeyeStorage syncStoreValue:withKey:inCollection:], /Pods/MTHawkeye/MTHawkeye/Core/MTHawkeyeStorage.m:123
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'line lenght should less than 16KB'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001158626fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000113ab9ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000115862482 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000113507927 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   MTHawkeye                           0x0000000110b661d1 -[MTHawkeyeStorage syncStoreValue:withKey:inCollection:] + 993
	5   MTHawkeye                           0x0000000110b65d23 __57-[MTHawkeyeStorage asyncStoreValue:withKey:inCollection:]_block_invoke + 51
	6   libdispatch.dylib                   0x0000000117d82d7f _dispatch_call_block_and_release + 12
	7   libdispatch.dylib                   0x0000000117d83db5 _dispatch_client_callout + 8
	8   libdispatch.dylib                   0x0000000117d8b225 _dispatch_lane_serial_drain + 778
	9   libdispatch.dylib                   0x0000000117d8be9c _dispatch_lane_invoke + 425
	10  libdispatch.dylib                   0x0000000117d95ea3 _dispatch_workloop_worker_thread + 733
	11  libsystem_pthread.dylib             0x0000000118231611 _pthread_wqthread + 421
	12  libsystem_pthread.dylib             0x00000001182313fd start_wqthread + 13
)
**To Reproduce**

点击事件中做了100w次循环

**Environment (please complete the following information):**

 - Device: iphone6s模拟器
 - OS: 12.2
 - Xcode Version: 10.2.1

**Additional context**
用的是swift4

**Comment by hello-david** [comment]
上述是报告一个NSInternalInconsistencyException异常，意思是

**Comment by hello-david** [comment]
上面描述信息是报告了一个NSInternalInconsistencyException异常，导致这个问题的原因是记录长度太长导致的。在MTHawkeyeStorage模块有这段逻辑`#ifdef DEBUG
    NSAssert(lineLength < 16 * 1024, @"line lenght should less than 16KB");
#endif`，测试流程建议看一下TimeConsumingDemoTableViewController这个Demo中的卡顿/卡死模拟。

**Comment by euanchan** [comment]
目前记录anr堆栈时，直接使用了 appenderfile 来记录，但 appenderfile 限制了最长的单条记录长度。
可以看下具体触发的实例，对比下现实中遇到的概率，如果有一定概率重现，可考虑将单条记录以一定的方式拆成多行存储，同时调整对应的读取逻辑

**Comment by guesspalm** [comment]
谢谢回复

**Comment by haowenwu** [comment]
这个问题在一些大型app里会频繁出现
debug 下会 assert 掉 正式包泄漏
具体的 @hello-david 会跟进了

**Comment by hello-david** [comment]
MTHANRHawkeyeAdaptor部分新增ANR消息大于16kb情况处理，在Debug模式下不会触发相应的断言
