### ISSUE TITLE
请问为什么pod后使用OneLine start没有内置Graphics(0.12版本)

### ISSUE THREAD

**Issue by LeeYZ** [meitu/MTHawkeye#42]
这是Pod的内容

pod 'MTHawkeye', :configurations => 'Debug'
  
  pod 'FLEX', :configurations => ['Debug']
  pod 'FBRetainCycleDetector', :configurations => ['Debug']
  pod 'fishhook', :configurations => ['Debug']
#  pod 'CocoaLumberjack', :configurations => ['Debug'] # CocoaLumberjack is optional, change to `MTHawkeye/DefaultPluginsWithoutLog` if don't need.
   pod 'MTGLDebug', :configurations => ['Debug'] # MTGLDebug is exclude by default, change `MTHawkeye` to `MTHawkeye/DefaultPlugins` to include.
  pod 'MTAppenderFile', :configurations => ['Debug']

**Comment by euanchan** [comment]
因不少项目可能 GLDebug 用不到，所以默认 hawkeye 没有引入。

需要手动再引入下 Graphics 内的插件

**Comment by hello-david** [comment]
在podfile中使用
```
  pod 'MTHawkeye/DefaultPlugins', :git => 'git@github.com:meitu/MTHawkeye.git', :configurations => ['Debug']
  pod 'MTGLDebug', :git => 'git@github.com:meitu/MTGLDebug.git', :configurations => ['Debug']
  pod 'FLEX', :configurations => ['Debug']
  pod 'FBRetainCycleDetector', :configurations => ['Debug']
  pod 'fishhook', :configurations => ['Debug']
```
在debug模式下引入Hawkeye目前所有的内置插件，在Appdelegate.m中添加以下代码启动便可以看到所有的插件（部分默认不开启）:
```
#ifdef DEBUG
#import <MTHawkeye/MTRunHawkeyeInOneLine.h>
#endif

#ifdef DEBUG
    [MTRunHawkeyeInOneLine start];
#endif
```
@LeeYZ 

根据Hawkeye.podspec里面写法会再引入GLDebug后会自动给工程注入宏定义MTH_INCLUDE_GLTRACE可能由于cocoapod的缓存问题未给工程注入这个宏定义，则这时候需要去清理一下Pods工程重新跑一下pod install，xcode看到MTHawkeyeDefaultPlugins.m的代码应该是
![](https://user-images.githubusercontent.com/17873903/66693741-f6432080-ecde-11e9-8eb2-5a08b425fb9a.png)
而不是👇这种错误情况：
![](https://user-images.githubusercontent.com/17873903/66693747-11ae2b80-ecdf-11e9-9197-f1906032dda3.png)

请注意是使用`MTHawkeye/DefaultPlugins`而非`MTHawkeye`这个podspec，假如后还是有问题可以在podfile中直接注入这个宏：
```
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        if target.name == 'MTHawkeye'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)','MTH_INCLUDE_GLTRACE=1']
                end
            end
        end
    end
end
```

如果实在不行请把MTHawkeyeDefaultPlugins.m中
```
#ifdef MTH_INCLUDE_GLTRACE
#endif
```
这段宏控制注释掉
