### ISSUE TITLE
真机崩

### ISSUE THREAD

**Issue by NXZXYMQ** [meitu/MTHawkeye#53]
iPhone8，iOS 13.3.1 真机启动Demo直接崩溃....

**Comment by panmingyang2009** [comment]
你好，能否提供一下崩溃的崩溃日志或堆栈信息 ，以供排查。
谢谢。

**Comment by NXZXYMQ** [comment]
dyld: Library not loaded: @rpath/libclang_rt.ubsan_ios_dynamic.dylib
  Referenced from: /private/var/containers/Bundle/Application/DD521C60-A6E3-456F-B9BA-47F30FF5247D/MTHawkeyeDemo.app/MTHawkeyeDemo
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/DD521C60-A6E3-456F-B9BA-47F30FF5247D/MTHawkeyeDemo.app/Frameworks/libclang_rt.ubsan_ios_dynamic.dylib: code signature invalid for '/private/var/containers/Bundle/Application/DD521C60-A6E3-456F-B9BA-47F30FF5247D/MTHawkeyeDemo.app/Frameworks/libclang_rt.ubsan_ios_dynamic.dylib'

**Comment by panmingyang2009** [comment]
谢谢

**Comment by hello-david** [comment]
是不是Xcode版本太低了，看日志是系统的库没找到？
