### ISSUE TITLE
项目中使用的AFNetworking的网络库，没有hook到项目中的任何请求

### ISSUE THREAD

**Issue by BingMax** [meitu/MTHawkeye#58]
**Describe the bug**
在项目我们使用自己封装的AFNetwroking网络请求库，但是使用了您的pod 库后，hook不到我们项目的任何请求，但是FLEX可以hook到

**Comment by hello-david** [comment]
不清楚你们内部的实现方式是如何的，有兴趣可以了解一下NetworkPlugin实现，就你这个问题而言可以在设置面部将NetworkMonitor/NetworkInspect模块关闭、或者通过[MTHawkeyeUserDefaults shared].networkInspectOn、[MTHawkeyeUserDefaults shared].networkMonitorOn在启动之前将模块关闭。

**Comment by euanchan** [comment]
> **Describe the bug**
> 在项目我们使用自己封装的AFNetwroking网络请求库，但是使用了您的pod 库后，hook不到我们项目的任何请求，但是FLEX可以hook到

用的 AFNetworking 是什么版本呢，有可能是 hook 实现的错误
