### ISSUE TITLE
使用FLEX heap Objects 必crash

### ISSUE THREAD

**Issue by zhipengbird** [meitu/MTHawkeye#6]
**Describe the bug**
使用内置的FLEX查看Heap Object必crash

**Screenshots**
![image](https://user-images.githubusercontent.com/7310464/56862029-291b8580-69d9-11e9-90d7-5f2b229a7257.png)

**Environment (please complete the following information):**
 - Device: iphone6sp
 - OS: 11.4
 - Xcode Version: 10.2.1

**Comment by euanchan** [comment]
试着关掉 UITimeProfiler 下的 Trace ObjC Call 功能，看下具体查看哪个 object 时遇到了崩溃。

另外 TraceObjCCall 功能只建议在查看主线程耗时方法时开启，平时调试时建议关闭。

**Comment by euanchan** [comment]
@zhipengbird 请问下是否还有再出现过呢

**Comment by zhipengbird** [comment]
目前正常使用，没有在复现了
