### ISSUE TITLE
开启 Allocation 之后启动就崩

### ISSUE THREAD

**Issue by tinymind** [meitu/MTHawkeye#71]
**Describe the bug**
开启 mtha_isAllocTracking 之后，再次启动 App，崩溃，如下图.
另外，FLEX 4.0.0 版本，不存在以下方法：
```
//MTHNetworkTransactionDetailTableViewController.m
detailViewController = [[FLEXImagePreviewViewController alloc] initWithImage:image]; // 改为 [FLEXImagePreviewViewController forImage:image];

//MTHDirectoryWatcherViewController.m
else if ([FLEXUtility isImagePathExtension:pathExtension]) { // 不存在 isImagePathExtension:
        UIImage *image = [UIImage imageWithContentsOfFile:fullPath];
        vc = [[FLEXImagePreviewViewController alloc] initWithImage:image]; // 改为 [FLEXImagePreviewViewController forImage:image];
    }
```

**Screenshots**
![image](https://user-images.githubusercontent.com/6042046/101746509-69743c80-3b06-11eb-8556-cb9bf7475e50.png)

**Environment (please complete the following information):**

 - Device: [e.g. iPhone 8]
 - OS: [e.g. iOS 14.2]
 - Xcode Version: [e.g. 12.2]
 - MTAppenderFile (0.4.4)
 - MTGLDebug (3.1.2)
 - MTHawkeye (0.11.4)
 - FLEX (= 4.0.0)

**Comment by haowenwu** [comment]
#55 

0.12.2 版本开始支持 FLEX 4.0+

**Comment by bestannwn** [comment]
遇到相同问题，开启 Allocation 后重启 app 会奔溃，

<img width="2434" height="355" alt="Image" src="https://github.com/user-attachments/assets/82389072-4165-49fe-abf8-d583f8d7372d" />
