### ISSUE TITLE
崩溃：-[NSURLResponse statusCode]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by puyang0521** [meitu/MTHawkeye#72]
**Describe the bug**
-[NSURLResponse statusCode]: unrecognized selector sent to instance

![image](https://user-images.githubusercontent.com/14015466/102042236-4dc1ac80-3e0c-11eb-9a8d-dd6a8d0b24fe.png)

 - Device: iPad 13.6
 - OS: 10.15.6
 - Xcode Version: 12.2

**Comment by haowenwu** [comment]
Please try #73
