### ISSUE TITLE
在不使用cocoapods的前提下，如何集成MTHawkeye?

### ISSUE THREAD

**Issue by fzq2016** [meitu/MTHawkeye#75]
由于项目历史比较久，不方便使用cocoapods，请问如何集成？谢谢。

**Comment by haowenwu** [comment]
下载源码拖入工程即可

**Comment by fzq2016** [comment]
我把源码中MTHawkeye文件夹直接拖到工程，会有很多编译错误咯。

![image](https://user-images.githubusercontent.com/17515624/107198423-0a607480-6a30-11eb-9c73-b1c511407576.png)
