### ISSUE TITLE
安装你的pod库时出现以下提示

### ISSUE THREAD

**Issue by zhipengbird** [meitu/MTHawkeye#9]
**Describe the bug**
安装该库时出现以下提示：
[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
请确认下podspec文件中是否有不规范的字符

**Environment (please complete the following information):**
 - pod Version: 1.5.0
 - Xcode Version: 10.2.1

**Comment by euanchan** [comment]
请检查下自己的 podfile 文件中，是否包含了全角的标点符号，如全角引号
